RL-61 | Add more logs

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,7 +37,6 @@ jobs:
           PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
           HOST: ${{ secrets.EC2_HOST }}
           USER: ${{ secrets.EC2_USER }}
-          SPRING_PROFILES_ACTIVE: 'prod'
         run: |
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           echo "Transferring JAR file to EC2..."
@@ -49,6 +48,16 @@ jobs:
             echo "Stopping existing application..."
             pkill -f RegaloLibre-0.0.1-SNAPSHOT.jar || true
             echo "Starting new application..."
-            SPRING_PROFILES_ACTIVE=prod nohup java -Dspring.profiles.active=prod -jar RegaloLibre-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
-            echo "Deployment complete."
+            cd ~
+            SPRING_PROFILES_ACTIVE=prod java -Dspring.profiles.active=prod -jar RegaloLibre-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+            sleep 10
+            if pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar > /dev/null
+            then
+              echo "Application started successfully"
+              tail -n 20 app.log
+            else
+              echo "Application failed to start"
+              cat app.log
+              exit 1
+            fi
           '
