RL-67 | Divide into smaller steps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,7 +46,7 @@ jobs:
           echo "Checking network connectivity to ${HOST} on port 22..."
           nc -zv ${{ secrets.EC2_HOST }} 22
 
-      - name: Deploy to EC2
+      - name: Transfer JAR to EC2
         env:
           PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
           HOST: ${{ secrets.EC2_HOST }}
@@ -57,31 +57,50 @@ jobs:
           scp -i private_key -o StrictHostKeyChecking=no -vvv RegaloLibre-0.0.1-SNAPSHOT.jar ${USER}@${HOST}:/home/ec2-user/RegaloLibre-0.0.1-SNAPSHOT.jar
           echo "Checking transferred file..."
           ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'ls -l /home/ec2-user/RegaloLibre-0.0.1-SNAPSHOT.jar'
-          echo "Deploying application on EC2..."
+
+      - name: Stop Existing Application
+        run: |
           ssh -i private_key -o StrictHostKeyChecking=no -vvv ${USER}@${HOST} '
-            echo "Checking for existing application process..."
-            ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
-            echo "Stopping existing application..."
-            PID=$(pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar)
-            if [ -n "$PID" ]; then
-            kill $PID
-            echo "Application stopped"
-            else
-            echo "No application process found"
-            fi
+          echo "Checking for existing application process..."
+          ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
+          echo "Stopping existing application..."
+          PID=$(pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar)
+          if [ -n "$PID" ]; then
+          kill $PID
+          echo "Application stopped"
+          else
+          echo "No application process found"
+          fi
+          '
+
+      - name: Start New Application
+        env:
+          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
+          HOST: ${{ secrets.EC2_HOST }}
+          USER: ${{ secrets.EC2_USER }}
+        run: |
+          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
             echo "Starting new application..."
             cd /home/ec2-user
-            nohup java -jar RegaloLibre-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
+            nohup SPRING_PROFILES_ACTIVE=prod java -jar RegaloLibre-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
             sleep 60
-            echo "Checking if application started..."
-            ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
-            if pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar > /dev/null
-            then
-              echo "Application started successfully"
-              tail -n 20 app.log
-            else
-              echo "Application failed to start"
-              cat app.log
-              exit 1
-            fi
           '
+      - name: Verify Application Start
+        env:
+          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
+          HOST: ${{ secrets.EC2_HOST }}
+          USER: ${{ secrets.EC2_USER }}
+          run: |
+            ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
+            echo "Checking if application started..."
+              ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
+              if pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar > /dev/null
+              then
+                echo "Application started successfully"
+                tail -n 20 app.log
+              else
+                echo "Application failed to start"
+                cat app.log
+                exit 1
+              fi
+            '
