RL-67 | Fix some syntax

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,7 @@ jobs:
 
       - name: Verify JAR File
         run: |
-          echo "Listing files in target directory..."
+          echo 'Listing files in target directory...'
           ls -l target/
 
       - name: Upload JAR
@@ -43,7 +43,7 @@ jobs:
 
       - name: Check connectivity
         run: |
-          echo "Checking network connectivity to ${HOST} on port 22..."
+          echo 'Checking network connectivity to ${HOST} on port 22...'
           nc -zv ${{ secrets.EC2_HOST }} 22
 
       - name: Transfer JAR to EC2
@@ -52,10 +52,10 @@ jobs:
           HOST: ${{ secrets.EC2_HOST }}
           USER: ${{ secrets.EC2_USER }}
         run: |
-          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-          echo "Transferring JAR file to EC2..."
+          echo '$PRIVATE_KEY' > private_key && chmod 600 private_key
+          echo 'Transferring JAR file to EC2...'
           scp -i private_key -o StrictHostKeyChecking=no -vvv RegaloLibre-0.0.1-SNAPSHOT.jar ${USER}@${HOST}:/home/ec2-user/RegaloLibre-0.0.1-SNAPSHOT.jar
-          echo "Checking transferred file..."
+          echo 'Checking transferred file...'
           ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'ls -l /home/ec2-user/RegaloLibre-0.0.1-SNAPSHOT.jar'
 
       - name: Stop Existing Application
@@ -94,17 +94,17 @@ jobs:
           PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
           HOST: ${{ secrets.EC2_HOST }}
           USER: ${{ secrets.EC2_USER }}
-          run: |
-            ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
-              echo "Checking if application started..."
-              ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
-              if pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar > /dev/null
-              then
-                echo "Application started successfully"
-                tail -n 20 /home/ec2-user/app.log
-              else
-                echo "Application failed to start"
-                cat /home/ec2-user/app.log
-                exit 1
-              fi
+        run: |
+          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
+            echo "Checking if application started..."
+            ps aux | grep RegaloLibre-0.0.1-SNAPSHOT.jar
+            if pgrep -f RegaloLibre-0.0.1-SNAPSHOT.jar > /dev/null
+            then
+              echo "Application started successfully"
+              tail -n 20 /home/ec2-user/app.log
+            else
+              echo "Application failed to start"
+              cat /home/ec2-user/app.log
+              exit 1
+            fi
             '
